version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPACY_MODEL=en_ner_bc5cdr_md
      - LINKER_NAME=rxnorm
      - LOG_LEVEL=INFO
      - DEBUG=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
