version: '3.8'

services:
  model:
    image: ghcr.io/yourusername/pill-checker-model:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 6G
    networks:
      - private_network

  core:
    image: ghcr.io/yourusername/pill-checker-core:latest
    env_file:
      - core.env
    ports:
      - "8000:8000"
    environment:
      BIOMED_HOST: "model:8081"
    restart: always
    networks:
      - private_network

  supabase-db:
    image: supabase/postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./migrations/001_init.sql:/docker-entrypoint-initdb.d/001_init.sql
      - supabase-db-data:/var/lib/postgresql/data
    networks:
      - private_network

networks:
  private_network:
    driver: bridge

volumes:
  supabase-db-data: