version: '3.8'

services:
  # Application service
  app:
    build:
      context: ../src/pill_checker
      dockerfile: Dockerfile
    ports:
      - "8080:8001"
    env_file:
      - .env
    networks:
      - supabase_network_core

networks:
  supabase_network_core:
    external: true
